# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000

create_project -in_memory -part xc7a100tcsg324-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/admin/OneDrive/Desktop/Vivado Projects/and/and.cache/wt} [current_project]
set_property parent.project_path {C:/Users/admin/OneDrive/Desktop/Vivado Projects/and/and.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {{C:/Users/admin/OneDrive/Desktop/Vivado Projects/and/and.srcs/sources_1/new/and_design_tb.v}}
read_xdc {{C:/Users/admin/OneDrive/Desktop/Vivado Projects/and/and.srcs/constrs_1/new/const_and.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/admin/OneDrive/Desktop/Vivado Projects/and/and.srcs/constrs_1/new/const_and.xdc}}]

catch { write_hwdef -file and_design_tb.hwdef }
synth_design -top and_design_tb -part xc7a100tcsg324-1
write_checkpoint -noxdef and_design_tb.dcp
catch { report_utilization -file and_design_tb_utilization_synth.rpt -pb and_design_tb_utilization_synth.pb }
