# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000

create_project -in_memory -part xa7a15tcpg236-2I
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/admin/OneDrive/Desktop/project_2_DP_RAM/project_2_DP_RAM.cache/wt [current_project]
set_property parent.project_path C:/Users/admin/OneDrive/Desktop/project_2_DP_RAM/project_2_DP_RAM.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib C:/Users/admin/OneDrive/Desktop/project_2_DP_RAM/project_2_DP_RAM.srcs/sources_1/new/DPRAM_design.v
catch { write_hwdef -file DPRAM.hwdef }
synth_design -top DPRAM -part xa7a15tcpg236-2I
write_checkpoint -noxdef DPRAM.dcp
catch { report_utilization -file DPRAM_utilization_synth.rpt -pb DPRAM_utilization_synth.pb }
