# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000

create_project -in_memory -part xa7a15tcpg236-2I
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/admin/OneDrive/Desktop/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/admin/OneDrive/Desktop/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib C:/Users/admin/OneDrive/Desktop/project_1/project_1.srcs/sources_1/new/Multiplier_Design.v
catch { write_hwdef -file Multiplier.hwdef }
synth_design -top Multiplier -part xa7a15tcpg236-2I
write_checkpoint -noxdef Multiplier.dcp
catch { report_utilization -file Multiplier_utilization_synth.rpt -pb Multiplier_utilization_synth.pb }
